cmake_minimum_required(VERSION 4.0)
project(LIS)

set(CMAKE_CXX_STANDARD 20)


add_executable(767A 767A.cpp)
add_executable(2234B 2234B.cpp)
add_executable(2234C 2234C.cpp)
add_executable(weird_algorithm cses/weird_algorithm.cpp)
add_executable(missing_number cses/missing_number.cpp)
add_executable(prefixsum cses/prefixsum.cpp)
add_executable(repetitions cses/repetitions.cpp)
add_executable(increasing_array cses/increasing_array.cpp)
add_executable(permutations cses/permutations.cpp)
add_executable(number_spiral cses/number_spiral.cpp)
add_executable(2240A 1105/2240A.cpp)
add_executable(two_sets cses/two_sets.cpp)
add_executable(bit_strings cses/bit_strings.cpp)
add_executable(couting_bits cses/couting_bits.cpp)
add_executable(grid_coloring_1 cses/grid_coloring_1.cpp)
add_executable(chessboard_and_queens cses/chessboard_and_queens.cpp)
add_executable(two_knights cses/two_knights.cpp)
add_executable(distinct_numbers cses/distinct_numbers.cpp)
add_executable(apartments cses/apartments.cpp)
add_executable(empty_string cses/empty_string.cpp)
add_executable(coin_piles cses/coin_piles.cpp)
add_executable(trailing_zeros cses/trailing_zeros.cpp)
add_executable(biagrams biagrams.cpp)
add_executable(Predominant Predominant.cpp)
add_executable(palindrome_reorder cses/palindrome_reorder.cpp)
add_executable(gray_code cses/gray_code.cpp)
add_executable(where_is_the_fire_station where_is_the_fire_station.cpp)
add_executable(tower_of_hanoi cses/tower_of_hanoi.cpp)
add_executable(dynamic_range_minimum_queries cses/dynamic_range_minimum_queries.cpp)
add_executable(unstable_elements unstable_elements.cpp)
add_executable(apple_division cses/apple_division.cpp)
add_executable(two_digit_strings two_digit_strings.cpp)
add_executable(galactic_cheese galactic_cheese.cpp)
add_executable(creating_strings cses/creating_strings.cpp)
add_executable(counting_rooms cses/counting_rooms.cpp)
add_executable(2246A 1108/2246A.cpp)
add_executable(2246B 1108/2246B.cpp)
add_executable(towers cses/towers.cpp)
