cmake_minimum_required(VERSION 4.0)
set(CMAKE_CXX_STANDARD 20)
project(problemsrepo)

add_executable(problemsrepo main.cpp)
add_executable(multiadder multiadder.cpp)
add_executable(colorcount colorcount.cpp)
add_executable(bottles bottles.cpp)
add_executable(toposort toposort.cpp)
add_executable(supershop supershop.cpp)
add_executable(staircase staircase.cpp)
add_executable(trianglesum trianglesum.cpp)
add_executable(binaryday3 binaryday3.cpp)
add_executable(trianglesummem trianglesummem.cpp)
add_executable(gridpath gridpath.cpp)
add_executable(consecutivesubsequence consecutivesubsequence.cpp)
add_executable(balancedbrackets balancedbrackets.cpp
        computergame.cpp)
add_executable(multidist multidist.cpp)
add_executable(signposting signposting.cpp)
add_executable(graphcomposition graphcomposition.cpp)
add_executable(dariuswisdom dariuswisdom.cpp)
add_executable(pashmakandparmidas pashmakandparmidas.cpp)
add_executable(socialnetwork socialnetwork.cpp)
add_executable(computergame computergame.cpp)
add_executable(sbb sbb.cpp)
add_executable(catering catering.cpp)
add_executable(baguettemagique baguettemagique.cpp
        gamblingdp.cpp)
add_executable(workingout workingout.cpp)
add_executable(stollencut stollencut.cpp)
add_executable(nastyaandpotions nastyaandpotions.cpp)
add_executable(bezhrubektreeeeeeeeeeeeee bezhrubektreeeeeeeeeeeeee.cpp)
add_executable(splitintotwosets splitintotwosets.cpp)
add_executable(gambling gambling.cpp)
add_executable(gamblingdp gamblingdp.cpp)
add_executable(rendezvousdemarinetrobin rendezvousdemarinetrobin.cpp)
add_executable(cutemall cutemall.cpp)
add_executable(shoplifting shoplifting.cpp)
add_executable(passingtheball passingtheball.cpp)
add_executable(spring spring.cpp)
add_executable(rightmax rightmax.cpp)
add_executable(sumofdigits sumofdigits.cpp)
add_executable(watercannon watercannon.cpp)
add_executable(zerotree zerotree.cpp)
add_executable(ardentflames ardentflames.cpp
)
add_executable(telepanting telepanting.cpp)
add_executable(escapethemaze escapethemaze.cpp
        escapethemaze.cpp)
add_executable(servertest servertest.cpp)
add_executable(fishing fishing.cpp)
add_executable(yoghurt yoghurt.cpp)
add_executable(angryducks angryducks.cpp)
add_executable(springsoi springsoi.cpp)
add_executable(segtree segtree.cpp)
add_executable(fastpow fastpow.cpp)
add_executable(premiereatwrongtime premiereatwrongtime.cpp)
add_executable(mysteriousscript mysteriousscript.cpp)
add_executable(zengarden zengarden.cpp)
add_executable(museum museum.cpp)
add_executable(stollencut3people stollencut3people.cpp)
add_executable(temp temp.cpp)
add_executable(gradingserver gradingserver.cpp
        gradingserver.cpp)
add_executable(whereisthefirestation whereisthefirestation.cpp)
add_executable(jzzhuandcities jzzhuandcities.cpp)
add_executable(whereami whereami.cpp)
add_executable(piecingittogether piecingittogether.cpp)
add_executable(queriesaboutlessorequal queriesaboutlessorequal.cpp)
add_executable(towers towers.cpp)
add_executable(newpalindrome newpalindrome.cpp)
add_executable(oddonecut oddonecut.cpp)
add_executable(shortestpath shortestpath.cpp)
add_executable(lehaandanothergameaboutgraph lehaandanothergameaboutgraph.cpp)
add_executable(numbers numbers.cpp)
add_executable(neuralfeud neuralfeud.cpp)
add_executable(boxesboxesboxes boxesboxesboxes.cpp)
add_executable(the67thintegerproblem the67thintegerproblem.cpp)
add_executable(2218B 2218B.cpp
        Recommendations.cpp)
add_executable(2218C 2218C.cpp)
add_executable(2218E 2218E.cpp)
add_executable(2218D 2218D.cpp)
add_executable(garland garland.cpp
        garland.cpp)
add_executable(Recommendations Recommendations.cpp
        Recommendations.cpp)
add_executable(balls balls.cpp)
add_executable(randomteams randomteams.cpp)
add_executable(blocked blocked.cpp)
add_executable(OIE_Excursion OIE_Excursion.cpp)
add_executable(gridL gridL.cpp)
add_executable(maxgeqsum maxgeqsum.cpp)
add_executable(ladder ladder.cpp)
add_executable(frog1 frog1.cpp)
add_executable(frog2 frog2.cpp)
add_executable(vacation vacation.cpp)
add_executable(knapsack1 knapsack1.cpp)
add_executable(longestpath longestpath.cpp)
add_executable(grid1 grid1.cpp)
add_executable(LCA LCA.cpp)
add_executable(restructuringcompany restructuringcompany.cpp)
add_executable(coins coins.cpp)
add_executable(eatinggame 800/2200A.cpp)
add_executable(2224A 2224A.cpp)
add_executable(rabbit rabbit.cpp)
add_executable(knight knight.cpp)
add_executable(king2 king2.cpp)
add_executable(slalom slalom.cpp)
add_executable(yadra yadra.cpp)
add_executable(fire fire.cpp)
add_executable(tombexploration tombexploration.cpp)
add_executable(longpath longpath.cpp)
add_executable(knapsack knapsack.cpp)
add_executable(peacefulsets peacefulsets.cpp)
add_executable(labyrinth labyrinth.cpp)
add_executable(moneybuyslesshappiness moneybuyslesshappiness.cpp)
add_executable(2228C1 2228C1.cpp)
add_executable(767A 767A.cpp)
add_executable(2234B 2234B.cpp)
add_executable(2234C 2234C.cpp)
add_executable(weird_algorithm cses/weird_algorithm.cpp)
add_executable(missing_number cses/missing_number.cpp)
add_executable(prefixsum cses/prefixsum.cpp)
add_executable(repetitions cses/repetitions.cpp)
add_executable(increasing_array cses/increasing_array.cpp)
add_executable(permutations cses/permutations.cpp)
add_executable(number_spiral cses/number_spiral.cpp)
add_executable(2240A 1105/2240A.cpp)
add_executable(two_sets cses/two_sets.cpp)
add_executable(bit_strings cses/bit_strings.cpp)
add_executable(couting_bits cses/couting_bits.cpp)
add_executable(grid_coloring_1 cses/grid_coloring_1.cpp)
add_executable(chessboard_and_queens cses/chessboard_and_queens.cpp)
add_executable(two_knights cses/two_knights.cpp)
add_executable(distinct_numbers cses/distinct_numbers.cpp)
add_executable(apartments cses/apartments.cpp)
add_executable(empty_string cses/empty_string.cpp)
add_executable(coin_piles cses/coin_piles.cpp)
add_executable(trailing_zeros cses/trailing_zeros.cpp)
add_executable(biagrams biagrams.cpp)
add_executable(Predominant Predominant.cpp)
add_executable(palindrome_reorder cses/palindrome_reorder.cpp)
add_executable(gray_code cses/gray_code.cpp)
add_executable(where_is_the_fire_station where_is_the_fire_station.cpp)
add_executable(tower_of_hanoi cses/tower_of_hanoi.cpp)
add_executable(dynamic_range_minimum_queries cses/dynamic_range_minimum_queries.cpp)
add_executable(unstable_elements unstable_elements.cpp)
add_executable(apple_division cses/apple_division.cpp)
add_executable(two_digit_strings two_digit_strings.cpp)
add_executable(galactic_cheese galactic_cheese.cpp)
add_executable(creating_strings cses/creating_strings.cpp)
add_executable(counting_rooms cses/counting_rooms.cpp)
add_executable(2246A 1108/2246A.cpp)
add_executable(2246B 1108/2246B.cpp)
add_executable(playlist cses/playlist.cpp)
add_executable(add_two_numbers leetcode/add_two_numbers.cpp)
add_executable(labyrinth_cses cses/labyrinth.cpp)
add_executable(building_roads cses/building_roads.cpp)
add_executable(dice_combinations cses/dice_combinations.cpp)
add_executable(minimizing_coins cses/minimizing_coins.cpp)
add_executable(coin_combinations cses/coin_combinations.cpp)
add_executable(building_teams cses/building_teams.cpp)
add_executable(message_route cses/message_route.cpp)
add_executable(monsters cses/monsters.cpp)
add_executable(shortest_path_I cses/shortest_path_I.cpp)
add_executable(shortest_path_II cses/shortest_path_II.cpp)
add_executable(round_trip cses/round_trip.cpp)
add_executable(lcs cses/lcs.cpp)
add_executable(template template.cpp)
add_executable(book_shop cses/book_shop.cpp)
add_executable(counting_towers cses/counting_towers.cpp)
add_executable(high_score cses/high_score.cpp)
add_executable(cycle_finding cses/cycle_finding.cpp)
add_executable(2251A 2251A.cpp)
add_executable(grid_path_I cses/grid_path_I.cpp)
add_executable(edit_distance cses/edit_distance.cpp)
add_executable(removing_digits cses/removing_digits.cpp)
add_executable(coin_combinations_II cses/coin_combinations_II.cpp)
add_executable(array_description cses/array_description.cpp)
add_executable(flight_routes cses/flight_routes.cpp)
add_executable(round_trip_II cses/round_trip_II.cpp)
add_executable(course_schedule cses/course_schedule.cpp)
add_executable(longest_flight_route cses/longest_flight_route.cpp)
add_executable(anysegtree anysegtree.cpp)
